#!/usr/bin/env bash

# Make Workspace
mkdir -p ~/Workspace/{bin,dev,git,tmp}
mkdir -p ~/.config/nvim

function install-vimplug() {
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

function install-prezto() {
    # Clone prezto
    git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

    # Make Configuration files
    setopt EXTENDED_GLOB
    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
        ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    done

    # Change default shell
    sudo chsh -s /bin/zsh
}

function links() {
    ln ~/.dotfiles/@/.zshrc ~/.zshrc
    ln ~/.dotfiles/@/.zpreztorc ~/.zpreztorc
    ln ~/.dotfiles/@/.tmux.conf ~/.tmux.conf
    ln ~/.dotfiles/@/init.vim ~/.config/nvim/init.vim
    ln ~/.dotfiles/@/.gitconfig ~/.gitconfig
}

if [[ "$OSTYPE" == "darwin"* ]]; then

    # Install brew
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    # Install vim-plug
    install-vimplug()

    # Install ZSH
    brew install zsh

    # Launch ZSH
    zsh

    # Set zsh + prezto
    install-prezto()

    # Link things
    links()

elif [[ "$OSTYPE" == "linux-gnu"* ]]; then

    # Change mirror
    sudo sed -i 's/archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list
    sudo apt update
    sudo apt install -y zsh curl ssh git neovim python3-dev python3-pip python3-setuptools

    # Install vim-plug
    install-vimplug()

    # Set zsh + prezto
    install-prezto()

    # Link things
    links()

else
    # WIP
fi
