#!/usr/bin/env bash

# Make Workspace
mkdir -p ~/Workspace/{bin,dev,git,tmp}
mkdir -p ~/.config/nvim

install-tpm () {
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}

install-vimplug() {
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

install-prezto() {
    # Clone prezto
    git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

    # Make Configuration files
    zsh -c "setopt EXTENDED_GLOB && for rcfile in \"${ZDOTDIR:-$HOME}\"/.zprezto/runcoms/^README.md(.N); do    
    ln -s \"\$rcfile\" \"${ZDOTDIR:-$HOME}/.\${rcfile:t}\"    
    done"

    # Change default shell
    sudo chsh -s $(grep /zsh$ /etc/shells | tail -1)
}

links() {
    echo $env
    ln -f ~/.dotfiles/@/.zshrc ~/.zshrc
    ln -f ~/.dotfiles/@/.zpreztorc ~/.zpreztorc
    ln -f ~/.dotfiles/@/.tmux.conf ~/.tmux.conf
    ln -f ~/.dotfiles/@/init.vim ~/.config/nvim/init.vim
    ln -f ~/.dotfiles/@/.gitconfig ~/.gitconfig
}

# Apple replaces default shell to zsh
if [[ "$OSTYPE" == "darwin"* ]]; then
    echo '[@] Installing osx environment'

    # Install brew
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    # Install tpm
    install-tpm

    # Install vim-plug
    install-vimplug

    # Set zsh + prezto
    install-prezto

    # Link things
    links

elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo '[@] Installing linux environment'

    # Change mirror (base Ubuntu 20.04)
    sudo apt update
    sudo apt install -y zsh curl ssh git neovim python3-dev python3-pip python3-setuptools

    # Install tpm
    install-tpm

    # Install vim-plug
    install-vimplug

    # Set zsh + prezto
    install-prezto

    # Link things
    links

else
    echo 'no match environment'
fi
