tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask"

tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "buo/cask-upgrade"

cask_args appdir: "/Applications"

# Brew
brew "autoenv"
brew "autojump"
brew "binwalk"
brew "fd"
brew "fzf"
brew "git"
brew "git-lfs"
brew "gist"
brew "jq"
brew "neovim"
brew "tmux"
brew "unzip"
brew "vim"
brew "wget"
brew "mysql", restart_service: true
brew "htop"
brew "socat"
brew "gpg"

# Applications
## Development
cask "docker"
cask "postman"
cask "visual-studio-code"
cask "sublime-text"
cask "sequel-pro-nightly"
cask "iterm2"
cask "intellij-idea"
cask "ngrok"

## Browsers
cask "google-chrome"
cask "firefox"

## Productivity
cask "alfred"
cask "typora"
cask "notion"
cask "slack"
cask "authy"
cask "toggl"

## Utilities
cask "imageoptim"
cask "tunnelblick"
cask "fantastical"
cask "pdf-expert"
cask "teamviewer"
cask "transmission"
