name: dotfiles
on:
  push:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --depth 1 https://github.com/seonggwonyoon/dotfiles.git ~/.dotfiles
      - run: ~/.dotfiles/install
  test-osx:
    runs-on: macos-latest
    steps:
      - run: git clone --depth 1 https://github.com/seonggwonyoon/dotfiles.git ~/.dotfiles
      - run: ~/.dotfiles/install
